### ISSUE TITLE
change output dir

### ISSUE THREAD

**Issue by karneaud** [aiba/ring-cljsbuild#1]
I have a configuration in my cljsbuild options 

```
:output-to "resources/public/js/main.js"
:output-dir "resources/public/js/out"
```

but seems to get ignored and builds to

> ring-cjlsbuild/ ......

How do i get to specify my own output path?

**Comment by aiba** [comment]
The idea behind this library/middleware was to remove the concept of files on disk from the application developer.  The clojurescript is only built to JS to be served by the HTTP server, and the fact that it happens to be cached on disk is just an implementation detail.

**Comment by karneaud** [comment]
too bloated though...
